Beatify/routes/admin.py
from flask import Blueprint, current_app, url_for, redirect, flash, render_template
from flask_login import login_user, login_required
from ..forms import AdminLoginForm
from ..models import User, Song, Album, Rating
from Beatify import db, mail
from ..utilities import role_needed, avg_rating_for_song, avg_creator_rating, show_stats
from flask_mail import Message

admin=Blueprint('admin',__name__)

@admin.route('/admin_login', methods=['POST', 'GET'])
def admin_login():
    form=AdminLoginForm()
    if form.validate_on_submit():
        if form.username.data==current_app.config['ADMIN_USERNAME'] and form.password.data==current_app.config['ADMIN_PASS']:
            admin=User.query.filter_by(username=form.username.data).first()
            login_user(admin)
            flash('Logged In as admin.', 'success')

            return redirect(url_for('admin.admin_dashboard'))
        else:
            flash('Login Unsuccessful. Please check Username and/or password',category='danger')
    return render_template('login.html', form=form, title='Admin Login', heading='Admin Login')

@admin.route('/admin_dashboard')
@login_required
@role_needed(roles=['admin'])
def admin_dashboard():
    users = User.query.all()
    creators = User.query.filter(User.roles.any(name='creator')).all()
    songs = Song.query.all()
    ratings = [avg_rating_for_song(Rating, song.id) for song in songs]
    albums = Album.query.all()
    show_stats(songs,ratings)
    return render_template('admin_page.html', title='Admin Dashboard', users=users, creators=creators, songs=songs, albums=albums)

@admin.route('/manage_data')
@login_required
@role_needed(roles=['admin'])
def manage_songs_albums():
    songs = Song.query.all()
    albums = Album.query.all()
    ratings = [avg_rating_for_song(Rating, song.id) for song in songs]
    return render_template('admin_songs_albums.html', title='Song and Albums', songs = songs, ratings=ratings, albums=albums)

@admin.route('/del_song_admin/<int:song_id>')
@login_required
@role_needed(roles=['admin'])
def delete_song_admin(song_id):
    Song.query.filter_by(id=song_id).delete()
    Rating.query.filter_by(song_id=song_id).delete()
    db.session.commit()
    return redirect(url_for('admin.manage_songs_albums'))

@admin.route('/del_album_admin/<int:album_id>')
@login_required
@role_needed(roles=['admin'])
def delete_album_admin(album_id):
    Album.query.filter_by(id=album_id).delete()
    db.session.commit()
    return redirect(url_for('admin.manage_songs_albums'))


@admin.route('/manage_creators')
@login_required
@role_needed(roles=['admin'])
def manage_creators():
    creators = User.query.filter(User.roles.any(name='creator')).all()
    song_id_list = [[song.id for song in creator.songs] for creator in creators]
    ratings = [avg_creator_rating(song_ids) for song_ids in song_id_list]
    return render_template('manage_creators.html', title='Manage Creators', creators=creators, ratings=ratings)

@admin.route('/blacklist_whitelist/<int:creator_id>')
@login_required
@role_needed(roles=['admin'])
def black_whitelist(creator_id):
    creator= User.query.get(creator_id)
    creator.is_blacklisted = not creator.is_blacklisted
    db.session.commit()
    return redirect(url_for('admin.manage_creators'))

Beatify/routes/main.py
from flask import Blueprint, render_template, make_response
from ..models import Song, User, Album


main=Blueprint('main',__name__)


@main.app_errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html", title='Page Not Found'), 404

@main.app_errorhandler(500)
def Internal_server_error(error):
    return render_template("errors/500.html", title='Internal Server Error'), 500

@main.app_errorhandler(403)
def unauthorized(error):
    return render_template("errors/403.html", title='Access Denied'), 403

@main.route('/')
def welcome():
    return render_template('welcome.html',title='Home')

@main.route('/display/user/<int:image_id>')
def load_user_image(image_id):
    user = User.query.get_or_404(image_id)
    response = make_response(user.profile)
    response.headers['Content-Type'] = 'image/jpeg' 
    return response

@main.route('/display/song/<int:song_id>')
def load_song(song_id):
    song = Song.query.get_or_404(song_id)
    response = make_response(song.song_file)
    response.headers['Content-Type'] = 'audio/mp3' 
    return response

@main.route('/display/song/image/<int:song_id>')
def load_song_image(song_id):
    song = Song.query.get_or_404(song_id)
    response = make_response(song.cover_file)
    response.headers['Content-Type'] = 'image/jpeg' 
    return response

@main.route('/display/album/image/<int:album_id>')
def load_album_image(album_id):
    album = Album.query.get_or_404(album_id)
    response = make_response(album.cover_file)
    response.headers['Content-Type'] = 'image/jpeg' 
    return response

Beatify/routes/users.py
from flask import Blueprint, jsonify
from Beatify import db, cache
from sqlalchemy import or_, and_
from werkzeug.security import generate_password_hash, check_password_hash
from flask import request, url_for, render_template, redirect, flash
from flask_login import login_user, current_user, logout_user, login_required
from ..models import LoginActivity, User, Role, Song, Rating, Playlist, Album, PlaylistSong, UserActivity
from ..utilities import role_needed, avg_rating_for_song, creatorreport
from ..tasks import userreminders, sendreports
from ..forms import LoginForm, RegistrationForm, CreatePlaylistForm, EditPlaylistForm
from sqlalchemy import func
from datetime import datetime

users = Blueprint('users', __name__)


@users.route('/search', methods=["POST", "GET"])
@login_required
@role_needed(roles=['user'])
def search():
    search_query = request.args.get('search_query')
    songs = Song.query.filter(
        or_(
            Song.lyrics.ilike(f"%{search_query}%"),
            Song.title.ilike(f"%{search_query}%"),
            Song.genre.ilike(f"%{search_query}%"),
            Song.album.has(Album.title.ilike(f"%{search_query}%")),
            Song.artist.has(User.name.ilike(f"%{search_query}%"))
        )
    ).all()
    albums = Album.query.filter(
        or_(
            Album.title.ilike(f"%{search_query}%"),
            Album.artist.has(User.name.ilike(f"%{search_query}%"))
        )
    ).all()
    return render_template('search.html', search_query=search_query, songs=songs, albums=albums, title='Search')


@users.route('/home')
@login_required
@role_needed(roles=['user'])
@cache.cached(timeout=60, key_prefix='home_songs')
def home_page():
    songs = Song.query.all()
    albums = Album.query.all()
    genres = [song.genre for song in songs]
    current_date = datetime.now().date()
    quer = LoginActivity.query.filter(
        and_(
            func.date(LoginActivity.datetime) == current_date,
            LoginActivity.user == current_user.id
        )
    ).all()
    if len(quer) == 0:
        lgact = LoginActivity(user=current_user.id)
        db.session.add(lgact)
        db.session.commit()
    return render_template('home.html', songs=songs, title='Home', albums=albums, genres=genres)


@users.route('/sign_up', methods=["POST", "GET"])
def sign_up():
    form = RegistrationForm()
    if form.validate_on_submit():
        user_role = Role.query.filter_by(name='user').first()
        hashed_pw = generate_password_hash(form.password.data)
        user = User(username=form.username.data, password=hashed_pw, email=form.email.data)
        user.roles.append(user_role)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data}! Please login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form, title='Sign Up')


@users.route('/login', methods=["POST", "GET"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            current_date = datetime.now().date()
            quer = LoginActivity.query.filter(
                and_(
                    func.date(LoginActivity.datetime) == current_date,
                    LoginActivity.user == current_user.id
                )
            ).all()
            if len(quer) == 0:
                lgact = LoginActivity(user=current_user.id)
                db.session.add(lgact)
                db.session.commit()
            return redirect(url_for('users.home_page'))
        else:
            flash('Invalid username and/or password. Please try again.', category='danger')
    return render_template('login.html', form=form, title='Login', heading='Login')


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.welcome'))


@users.route('/account')
@login_required
@role_needed(roles=['user'])
def account():
    return render_template('account.html', title='Account')


@users.route('/song/<int:song_id>')
@login_required
@role_needed(roles=['user'])
def song(song_id):
    song = Song.query.get(song_id)
    avg_rating = round(avg_rating_for_song(Rating, song_id), 2)
    num = len(Rating.query.filter_by(song_id=song_id).all())
    db.session.commit()
    return render_template('song.html', song=song, title=song.title, num=num, avg_rating=avg_rating)


@users.route('/rating/<int:song_id>/<int:value>')
@login_required
@role_needed(roles=['user'])
def rate(song_id, value):
    rating = Rating.query.filter_by(user_id=current_user.id, song_id=song_id).first()
    if rating is None:
        db.session.add(Rating(user_id=current_user.id, song_id=song_id, rating=value))
        db.session.commit()
    else:
        rating.rating = value
        db.session.commit()
    return redirect(url_for('users.song', song_id=song_id))


@users.route('/album/<int:album_id>')
@login_required
@role_needed(roles=['user'])
def album(album_id):
    album = Album.query.get(album_id)
    return render_template('album.html', album=album, title=album.title)


@users.route('/playlists')
@login_required
@role_needed(roles=['user'])
def playlists():
    playlists = current_user.playlists
    return render_template('playlists.html', title='Playlists', playlists=playlists)


@users.route('/playlist/<int:playlist_id>', methods=["POST", "GET"])
@login_required
@role_needed(roles=['user'])
def playlist(playlist_id):
    playlist = Playlist.query.get(playlist_id)
    return render_template('playlist.html', title='Playlist', playlist=playlist)


@users.route('/create_playlists', methods=["POST", "GET"])
@login_required
@role_needed(roles=['user'])
def create_playlists():
    form = CreatePlaylistForm()
    form.songs.query = [song for song in Song.query.all()]
    if form.validate_on_submit():
        selected_songs = form.songs.data
        playlist = Playlist(name=form.title.data, user_id=current_user.id)
        for song in selected_songs:
            playlist.songs.append(song)
        db.session.add(playlist)
        db.session.commit()
        return redirect(url_for('users.playlists'))
    return render_template('create_playlist.html', title='Create', form=form, Song=Song)


@users.route('/delete_playlist/<int:playlist_id>')
@login_required
@role_needed(roles=['user'])
def remove_playlist(playlist_id):
    playlist = Playlist.query.get(playlist_id)
    if current_user.id != playlist.user_id:
        return redirect(url_for('users.playlists'))
    PlaylistSong.query.filter_by(playlist_id=playlist_id).delete()
    Playlist.query.filter_by(id=playlist_id).delete()
    db.session.commit()
    return redirect(url_for('users.playlists'))


@users.route('/edit_playlist/<int:playlist_id>', methods=["POST", "GET"])
@login_required
@role_needed(roles=['user'])
def edit_playlist(playlist_id):
    playlist = Playlist.query.get(playlist_id)
    if current_user.id != playlist.user_id:
        return redirect('users.playlists')
    form = EditPlaylistForm()
    form.songs.query = [song for song in Song.query.all()]
    # initial values
    if request.method == 'GET':
        form.title.data = playlist.name
    if form.validate_on_submit():
        # values after editing
        playlist.title = form.title.data
        selected_songs = form.songs.data
        if selected_songs:
            playlist.songs = []
            for song in selected_songs:
                playlist.songs.append(song)
        db.session.commit()
        return redirect(url_for('users.playlists'))
    return render_template('edit_playlist.html', form=form, title="Edit Playlist")


@users.route('/song_played', methods=['POST'])
@login_required
@role_needed(roles=['user'])
def song_played():
    data = request.get_json()
    song_id = data.get('song_id')

    if song_id is not None:
        activity = UserActivity(user=current_user.id, activity='SongPlay', song=song_id)
        db.session.add(activity)
        db.session.commit()

        return jsonify({'message': 'Activity recorded'}), 200
    else:
        return jsonify({'message': 'Invalid request'}), 400

Beatify/templates/account.html
{% extends "layout.html" %}

{%block title%}{{super()}}{%endblock%}
{%block content%}
{{super()}}
<div class="container mt-5">
    <div class="rounded-circle w-100">
        {% if current_user.profile%}
            <img src="{{url_for('main.load_user_image', image_id=current_user.id)}}">
        {%endif%}
    </div>
    <h1>Description </h1>
    <div>Username : {{current_user.username}}</div>
    {% if current_user.name%}
    <div>Name : {{current_user.name}}</div>
    {% endif %}
    <div>Email : {{current_user.email}}</div>
    <div>Status : {{current_user.roles}}</div>
    {% if current_user.description%}
    <div>More : {{current_user.description}}</div>
    {%endif%}
</div>
{%endblock%}

Beatify/templates/admin_songs_albums.html
{% extends "layout.html" %}
{%block title%}{{super()}}{%endblock%}
{%block content%}
{{super()}}
<div class="container mt-5" >
    <section class="my-5">
        <h1>Songs</h1><br>
        <table class="table table-hover table-bordered">
            <thead>
              <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Artist</th>
                <th>Rating</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {%for i in range(songs|length)%}
                <tr class="">
                    <td class="align-middle">{{songs[i].title}}</td>
                    <td class="align-middle">{{songs[i].genre}}</td>
                    <td class="align-middle">{{songs[i].artist.name}}</td>
                    <td class="align-middle">{{ratings[i]}}</td>
                    <td class="align-middle">
                        <a class="btn btn-outline-danger" href="{{url_for('admin.delete_song_admin',song_id=songs[i].id)}}" role="button">
                            <i class="bi bi-flag"></i>/<i class="bi bi-trash"></i>
                        </a>                    
                    </td>
                </tr>
              {%endfor%}
            </tbody>
          </table>
        </div>
    </section>
    <section class="my-5">
        <h1>Albums</h1><br>
        <table class="table table-hover table-bordered">
            <thead>
              <tr>
                <th>Title</th>
                <th>Artist</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {%for i in range(albums|length)%}
                <tr class="">
                    <td class="align-middle">{{albums[i].title}}</td>
                    <td class="align-middle">{{albums[i].artist.name}}</td>
                    <td class="align-middle">
                        <a class="btn btn-outline-danger" href="{{url_for('admin.delete_album_admin',album_id=albums[i].id)}}" role="button">
                            <i class="bi bi-flag"></i>/<i class="bi bi-trash"></i>
                        </a>                    
                    </td>
                </tr>
              {%endfor%}
            </tbody>
          </table>
        </div>
    </section>
</div>
{%endblock%}



    

Beatify/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {%block head%}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>{%block title%}{{title}}{%endblock%}</title>
    <link rel="stylesheet" href="{{url_for('static',filename='styles/style.css')}}">
    <!-- Option 1: Include in HTML -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    {%endblock%}
</head>
<body>
  {% set user_roles = current_user.roles | map(attribute='name') | list %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm py-4">
        <div class="container">
          <a class="navbar-brand" href="#">BEATIFY</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
            {% if current_user.is_authenticated%}
              {%if 'user' in user_roles %}
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('users.home_page')}}">Home</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="playlistDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Playlists
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="playlistDropdown">
                    <li><a class="dropdown-item" href="{{url_for('users.playlists')}}">View Playlists</a></li>
                    <li><a class="dropdown-item" href="{{url_for('users.create_playlists')}}">Create Playlists</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
                </li>
                {% if 'creator' in user_roles %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-info" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Create
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{url_for('creators.create_songs')}}">Song</a></li>
                    <li><a class="dropdown-item" href="{{url_for('creators.create_album')}}">Album</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-info" href="{{url_for('creators.profile')}}">Profile</a>
                </li>
                {%else%}
                <li class="nav-item">
                  <a data-toggle="tooltip" data-placement="top" title="Upgrade to Creator" class="nav-link text-info fw-bold" href="{{url_for('creators.upgarde_to_creator')}}">Upgrade </a>
                </li>
                {% endif %}

                <form method="GET" action="{{url_for('users.search')}}" class="me-5" autocomplete="off" novalidate>
                  <div class="input-group">
                      <input type="text" class="form-control rounded-end-0" name="search_query" placeholder="Search...">
                      <div class="input-group-append">
                          <button class="btn btn-primary rounded-start-0" type="submit">
                            <i class="bi bi-search"></i>
                          </button>
                      </div>
                  </div>
                </form>
              {%endif%}

              {% if 'admin' in user_roles%}
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('admin.admin_dashboard')}}">Dashboard</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('admin.manage_songs_albums')}}">Songs and Albums</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('admin.manage_creators')}}">Creators</a>
                </li>
              {%endif%}
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
                </li>
            {%else%}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('users.sign_up')}}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('users.login')}}">Log In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.admin_login')}}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/">Go Back</a>
              </li>
            {%endif%}
            </ul>
          </div>
        </div>
      </nav>
    
    <div class="container" >
    {%block content%}
        {% block flash %}
            {% with messages=get_flashed_messages(with_categories=True)%}
                {% for category, message in messages%}
                    <div class="alert alert-{{category}}  show fade mt-2" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {%endwith%}
        {% endblock %}
    {%endblock%}   
    </div>

    {%block scripts%}           
    {%endblock%}

<script>
  document.addEventListener('DOMContentLoaded', function () {
      var tooltips = [].slice.call(document.querySelectorAll('[data-toggle="tooltip"]'));
      tooltips.forEach(function (tooltip) {
          new bootstrap.Tooltip(tooltip);
      });
  });
</script>

</body>
</html>

Beatify/templates/playlists.html
{% extends "layout.html" %}

{%block title%}{{super()}}{%endblock%}
{%block content%}
{{super()}}
<div class="container p-5 border my-3 border-1">
    <h2 class="text-primary text-center">Playlists</h2>
    {% if playlists%}
    {% for playlist in playlists%}
            <div class="fs-4 mt-3 border border-primary rounded-2">
                    <div class="song-item p-3 d-flex flex-wrap align-items-center" style="gap:20px;">
                        <div class="rounded-3"><img src="{{url_for('static', filename='images/default_playlist.jpg')}}" width="80px"></div>
                        <div>
                            <a href="{{url_for('users.playlist', playlist_id=playlist.id)}}">
                            {{playlist.name}}
                            </a>
                        </div>
                        <div class="btn-toolkit ms-auto">
                            
                                <a href="{{url_for('users.edit_playlist', playlist_id = playlist.id)}}" class="btn btn-lg btn-outline-primary" role="button">
                                    <i class="bi bi-pen"></i>
                                </a>
                            
        
                                <a class="btn btn-lg btn-outline-danger" href="{{url_for('users.remove_playlist',playlist_id=playlist.id)}}" role="button">
                                    <i class="bi bi-trash"></i>
                                </a>
                            
                        </div>
                    </div>
            </div>    
    {% endfor %}
    {%else%}
        <div class="text-danger text-center">
            You do not have any playlists T_T. <br>
            Click <a href="{{url_for('users.create_playlists')}}">here</a> to start creating one.      
        </div>
    {%endif%}
</div>
{%endblock%}

Beatify/templates/search.html
{% extends "layout.html" %}

{% block head %}{{super()}}{%endblock%}
{%block title%}{{super()}}{%endblock%}
{%block content%}
{{super()}}
<div class="container head mb-3 p-5 rounded-1 ">
    <h1 >You searched for: '{{search_query}}'</h1>
     <div id="ratingFilter">
        <input type="range" min="1" max="5" value="1" class="slider" id="ratingSlider">
        <p>Rating: <span id="ratingValue"></span></p>
    </div>


    {% if albums or songs %}
    <hr>

        {%for song in songs%}
        <a href="{{url_for('users.song', song_id=song.id)}}" class="text-decoration-none">
            <div class="search-item p-3 d-flex flex-wrap align-items-center" data-rating="{{song.avg_rating()}}" style="gap:10px">

                {% if song.cover_file%}
                <div style="width:auto"><img src="{{url_for('main.load_song_image', song_id=song.id)}}" width="100px" alt=""></div>
                {%else%}
                <div style="width:auto"><img src="{{url_for('static', filename='images/default.jpg')}}" width="100px" alt=""></div>
                {%endif%}
                <div>
                    <div>{{song.title}}</div>
                    <div>{{song.genre}}</div>
                    <div>{{song.artist.name}}</div>
                </div>
            </div>
        </a>
        {%endfor%}
        {% if albums%}
            <h3 class="text-primary mt-3">Albums :</h3> 
            <hr>
        {%endif%}
        {%for album in albums%}
        
        <a href="{{url_for('users.album',album_id=album.id)}}" class="text-decoration-none">
            <div class="search-item p-3 d-flex flex-wrap align-items-center" style="gap:10px">
                {% if album.cover_file%}
                <div style="width:auto"><img src="{{url_for('main.load_album_image', album_id=album.id)}}" width="100px" alt=""></div>
                {%else%}
                <div style="width:auto"><img src="{{url_for('static', filename='images/default_album.png')}}" width="100px" alt=""></div>
                {%endif%}
                <div>
                    <div>{{album.title}}</div>
                    <div>{{album.artist.name}}</div>
                </div>
            </div>
        </a>
        {%endfor%}

        <script>
            var slider = document.getElementById("ratingSlider");
            var output = document.getElementById("ratingValue");
            output.innerHTML = slider.value;

            slider.oninput = function() {
                output.innerHTML = this.value;
                var rating = this.value;
                var songs = document.getElementsByClassName("search-item");
                for (var i = 0; i < songs.length; i++) {
                    var songRating = Math.floor(songs[i].getAttribute("data-rating"));
                    if (!songRating || songRating == rating) {
                        songs[i].classList.add("d-flex");
                        songs[i].style.display = "flex";
                    } else {
                        songs[i].classList.remove("d-flex");
                        songs[i].style.display = "none";
                    }
                }
            }
        </script>
    {%else%}
        <div class="text-danger text-center">No result matches your search :((</div>
    {%endif%}

    
</div>


{%endblock%}

Beatify/templates/song.html
{% extends "layout.html" %}

{%block title%}{{super()}}{%endblock%}
{%block content%}
{{super()}}
<div class="container mb-3" >
    <div class="row mt-5 justify-content-md-center gx-5">
    <div class="col-md-4">
    {{super()}}
    <div class="card song-card">
        {% if song.cover_file%}
        <img src="{{url_for('main.load_song_image', song_id = song.id)}}" class="card-img-top" alt="Song Cover" loading="eager">
        {%else%}
        <img src="{{url_for('static', filename='images/default.jpg')}}" alt="">
        {%endif%}
        <div class="card-body song-card-body">
          <h1 class="card-title">{{song.title}}</h1>
          <h6 class="card-text">{{song.artist.name}}</h6>
          <p class="card-text">{{song.genre}}</p>
          <p class="card-text">{{song.date_uploaded.strftime('%Y-%m-%d')}}</p>
          <p class="card-text">{% if avg_rating %}{{avg_rating}} 🌟 ({{num}}){% else %}<span class="fw-bold">Unrated</span>{%endif%}</p>
          <audio id="song" controls>
            <source src="{{url_for('main.load_song', song_id = song.id)}}" type="audio/mp3">
            Your browser does not support the audio element.
        </audio>

        <script>
        var song = document.getElementById('song');
        var apiCalled = false;

        song.addEventListener('timeupdate', function() {
            if (!apiCalled && song.currentTime >= song.duration / 2) {
                apiCalled = true;
                sendPlayEvent({{ song.id }});
            }
        });

        function sendPlayEvent(songId) {
            fetch("{{ url_for('users.song_played') }}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({ song_id: songId })
            });
        }
        </script>
        </div>
        <div class="card-footer">
            <div class="btn-group mt-2">
                <button type="button" class="btn btn-outline-primary dropdown-toggle" id="ratingDropdown" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Rate
                </button>
                <div class="dropdown-menu" aria-labelledby="ratingDropdown">
                    {% for rating in range(1, 6) %}
                    <a class="dropdown-item" href="{{ url_for('users.rate', song_id=song.id, value=rating) }}">{{ rating }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
        <div class="col-md-5">
            <h2 class="mt-5 text-primary">Lyrics</h2>
            
            <p>
            <pre style="font-family:Verdana, Geneva, Tahoma, sans-serif">
            {{song.lyrics|safe}}
            </pre>
            </p>
        </div>
    </div>

<hr>

</div>
{%endblock%}